//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAoTreEm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VN_ProvincesEntities : DbContext
    {
        public VN_ProvincesEntities()
            : base("name=VN_ProvincesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<ward> wards { get; set; }
    }
}
